export const thirdFunction = () => {
    throw new Error("error in thirdFunction");
}